name: Photodash
description: An easy to configure, photo focused Home Assistant alternative dashboard
version: 0.2.3
slug: photo_dash
init: false
arch:
  - aarch64
  - amd64
image: apopoutsis/{arch}-photodash
startup: before
ports:
  3000/tcp: 8800
services:
  - mysql:need
map:
  - share
webui: http://[HOST]:[PORT:3000]
url: https://photodash.apop.tech
